package Episante.back.Models;

public enum Specialite {
    CARDIOLOGIE,
    DERMATOLOGIE,
    GYNECOLOGIE,
    PEDIATRIE,
    ORTHOPEDIE,
    GENERALISTE,
    OPHTALMOLOGIE,
    NEUROLOGIE,
    ENDOCRINOLOGIE,
    PSYCHIATRIE
}